<?php
/*------------------------------------------------------------------------
 # SM Featured Category - Version 1.0.0
 # Copyright (c) 2015 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

$image_config_odd = array(
    'width' => (int)$this->_getConfig('imgcfg_width', 250),
    'height' => $this->_getConfig('imgcfg_height', 370),
    'constrainOnly' => true,
    'keepAspectRatio' => false,
    'keepFrame' => true,
    'keepTransparency' => true,
    'background' => '#FFFFFF',
    'function' => true
);

$image_config_even = array(
    'width' => (int)$this->_getConfig('imgcfg_width', 310),
    'height' => $this->_getConfig('imgcfg_height', 450),
    'constrainOnly' => true,
    'keepAspectRatio' => false,
    'keepFrame' => true,
    'keepTransparency' => true,
    'background' => '#FFFFFF',
    'function' => true
);

$helper = Mage::helper('featuredcategory/data');
$child_items = $items->child;
if (!empty($child_items)) {
    $stt = 0;
    foreach ($child_items as $_product) {
        $stt++;
        ?>
            <div class="fc-item-inner">

                <div class="item-stt">
                    <?php echo $stt;?>
                </div>

                <div class="item-infor">
                    <?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
                        <div class="item-title">
                            <a href="<?php echo $_product->link; ?>"
                               title="<?php echo $_product->title; ?>"
							   <?php echo $helper->parseTarget($this->_getConfig('link_target')); ?> >
                                <?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength', 25)); ?>
                            </a>
                        </div>
                    <?php } ?>

                    <?php if ((int)$this->_getConfig('product_description_display', 1) && $_product->_description != '') { ?>
                        <div class="item-description">
                            <?php echo $_product->_description; ?>
                        </div>
                    <?php } ?>

                    <?php if ((int)$this->_getConfig('product_reviews_count', 1) && $_product->num_rating_summary != null) { ?>
                        <div class="item-review">
                            <?php
                            $this->addReviewSummaryTemplate('sm', 'sm/extraslider/default_summary.phtml');
                            echo $this->getReviewsSummaryHtml($_product, 'sm', false);
                            ?>
                        </div>
                    <?php } ?>

                    <?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
                        <div class="item-price">
                            <div class="sale-price">
                                <?php echo $this->getPriceHtml($_product, true); ?>
                            </div>
                        </div>
                    <?php } ?>

                    <?php if ((int)$this->_getConfig('product_addcart_display', 1)) { ?>
                        <?php if ($_product->isSaleable()) { ?>
                            <p class="item-addcart">
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>"
                                        class="button btn-cart"
                                        onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                            <span>
                                <span>
                                    <?php echo $this->__('Add to Cart') ?>
                                </span>
                            </span>
                                </button>
                            </p>
                        <?php } else { ?>
                            <p class="availability out-of-stock">
                    <span>
                        <?php echo $this->__('Out of stock') ?>
                    </span>
                            </p>
                        <?php } ?>
                    <?php } ?>

                    <?php if ((int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) { ?>
                        <ul class="add-to-links">
                            <?php if ((int)$this->_getConfig('product_addwishlist_display', 1)) { ?>
                                <?php if ($this->helper('wishlist')->isAllow()) { ?>
                                    <li>
                                        <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"
                                           class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            <?php } ?>

                            <?php if ((int)$this->_getConfig('product_addcompare_display', 1)) { ?>
                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)) { ?>
                                    <li>
                                        <span class="separator">|</span>
                                        <a href="<?php echo $_compareUrl ?>"
                                           class="link-compare"><?php echo $this->__('Add to Compare') ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            <?php } ?>
                        </ul>
                    <?php } ?>

                    <?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
                        <div class="item-readmore">
                            <a href="<?php echo $_product->link; ?>"
                               title="<?php echo $_product->title; ?>" <?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?> >
                                <?php echo $this->_getConfig('product_readmore_text'); ?>
                            </a>
                        </div>
                    <?php } ?>
                </div>
            </div>
    <?php }
} ?>