<?php $posts = $this->getPosts(); ?>
<?php
	
?>
<div class="block latest-blog">
	<h2 class="block-title">
		<?php echo $this->__('From the blog')?>
	</h2>
	<div class="desc-title"><p>Read all blog posts</p></div>	
	
	<div class="block-content">
		<div class="latest-blog-slider">
			<?php $i=0; foreach ($posts as $post): ?>
			<div class="item-blog item">
				<div class="item-blog-inner">
					<?php
						$pattern = "/<img .+\/>/";
						$subject = $post->getPostContent();
						$result = preg_match( $pattern, $subject , $matches , PREG_OFFSET_CAPTURE );
						$matched =$matches[0];
						$first_img=$matched[0];
					?>
					<div class="img-blog">
						<a class="img-link" title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo($first_img);?></a>
					</div>
					<div class="blog-info">
						<div class="postTitle">
							<h2><a title="<?php echo $post->getTitle(); ?>" href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
						</div>
						
						<div class="postContent">
							<?php $text = str_replace($first_img, '', $post->getPostContent()); 
								$html = strip_tags($text);
								echo substr($html,1,150);
							?>
						</div>
						<div class="button-wrap"><a class="button readmore" href="<?php echo $post->getAddress(); ?>">Read more</a></div>
					</div>
				</div>
			</div>
			<?php $i++;?>
			
			<?php if($i==3) break;?>
			<?php endforeach; ?>
		</div>
	</div>

</div>