<?php
/*------------------------------------------------------------------------
 # SM Shop By - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
?>

<?php
$product = Mage::registry('ingram_category');
$_productCollection = $product->Book;
$_helper = $this->helper('catalog/output');
//echo "<pre>"; print_r($_productCollection); die;
?>

<?php if (!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php if (!$this->getRequest()->isAjax()): ?>
        <div id="ajax-errors" style="display: none;">
            <ul class="messages">
                <li class="error-msg">
                    <ul>
                        <li><span><?php echo $this->__('An error occurred, please try again later.'); ?></span></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div id="loading" style="display: none; margin-bottom: 10px; text-align: center;">
            <img class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/loading-qv.gif'); ?>">
        </div>

<div id="catalog-listing">
    <?php endif; ?>
    <div class="category-products">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product):
                    $id_product = Mage::getModel('catalog/product')->load($_product->getId());
                    //$count_input_qty++;
                    $now = date("Y-m-d");
                    $newsFrom = substr($_product->getData('news_from_date'), 0, 10);
                    $newsTo = substr($_product->getData('news_to_date'), 0, 10);

                    $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
                    //echo $specialprice . '-hau<br/>';
                    $price = Mage::getModel('catalog/product')->load($_product->getId())->getPrice();
                    if ($specialprice == '') {
                        $store_id = Mage::app()->getStore()->getStoreId();
                        $discounted_price = Mage::getResourceModel('catalogrule/rule')->getRulePrice(
                            Mage::app()->getLocale()->storeTimeStamp($store_id),
                            Mage::app()->getStore($store_id)->getWebsiteId(),
                            Mage::getSingleton('customer/session')->getCustomerGroupId(),
                            $_product->getId());
                        $specialprice = $discounted_price;

                    }

                    ?>
                    <div class="item respl-item<?php echo ($newsFrom != "" && $now >= $newsFrom && ($now <= $newsTo || $newsTo == "") || $specialprice)? " haslabel":""; ?>">
						<?php if ($newsFrom != "" && $now >= $newsFrom && ($now <= $newsTo || $newsTo == "")) { ?>
							<div class="new-item<?php echo ($specialprice)? " label2":""; ?>">
								<span class="txt-label"><?php echo $this->__('New') ?></span>
							</div>
						<?php } ?>

						<?php if ($specialprice) { ?>
							<div class="sale-item<?php echo ($newsFrom != "" && $now >= $newsFrom && ($now <= $newsTo || $newsTo == ""))? " label2":""; ?>">
								<span class="txt-label"><?php echo $this->__('Sale') ?></span>
							</div>
						<?php } ?>	
											
                        <div class="item-inner">
                            <div class="w-image-box">
                                <div class="item-image">
                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"
                                       class="product-image">
									   <img id="product-collection-image-<?php echo $_product->getId(); ?>"
                                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(196,306); ?>"
                                            alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>"/></a>
											
									<?php
									// Provides extra blocks on which to hang some features for products in the list
									// Features providing UI elements targeting this block will display directly below the product name
									if ($this->getChild('name.after')) {
										$_nameAfterChildren = $this->getChild('name.after')->getSortedChildren();
										foreach ($_nameAfterChildren as $_nameAfterChildName) {
											$_nameAfterChild = $this->getChild('name.after')->getChild($_nameAfterChildName);
											$_nameAfterChild->setProduct($_product);
											echo $_nameAfterChild->toHtml();
										}
									}
									?>
                                </div>


                            </div>

							<div class="w-info-box">
								<div class="item-info">
									
									<div class="item-title">
										<a href="<?php echo $_product->getProductUrl() ?>"
										   title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
									</div>
								
									<div class="item-review">
										<?php echo $this->getReviewsSummaryHtml($_product, "short", true); ?>
									</div>

									<div class="item-price">
										<?php echo $this->getPriceHtml($_product, true) ?>
									</div>
									
									<div class="desc std">
										<?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
									</div>								
								</div>

								<div class="item-action">
									<?php if ($_product->isSaleable()): ?>
										<button title="<?php echo $this->__('Add to Cart')?>" type="button" class="btn-pd btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
											<span>
												<span><?php echo $this->__('Add to Cart') ?></span>
											</span>
										</button>
									<?php else: ?>
										<p class="availability out-of-stock">
											<span><?php echo $this->__('Out of stock') ?></span>
										</p>
									<?php endif; ?>		

								
									<a style="display:none;" href="<?php echo $_product->getProductUrl() ?>"></a>
									<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<a data-toggle="tooltip" data-placement="top"  title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="btn-pd item-wishlist">
											<span><?php echo $this->__('Add to Wishlist') ?></span>
										</a>
									<?php endif; ?>		

									<?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
										<a data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Add to Compare') ?>" href="<?php echo $_compareUrl ?>" class="btn-pd item-compare">
											<span><?php echo $this->__('Add to Compare') ?></span>
										</a>
									<?php endif; ?>								
								</div>
									
							</div>

                        </div>
                    </div>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->count() ?>
        <?php $_columnCount = $this->getColumnCount(); ?>
            <div class="products-grid row">
                <?php $i = 0;
                foreach ($_productCollection as $_product):

//echo "<pre>"; print_r($_product); die;

                    /*$id_product = Mage::getModel('catalog/product')->load($_product->getId());
                    //$count_input_qty++;
                    $now = date("Y-m-d");
                    $newsFrom = substr($_product->getData('news_from_date'), 0, 10);
                    $newsTo = substr($_product->getData('news_to_date'), 0, 10);

                    $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
                    //echo $specialprice . '-hau<br/>';
                    $price = Mage::getModel('catalog/product')->load($_product->getId())->getPrice();
                    if ($specialprice == '') {
                        $store_id = Mage::app()->getStore()->getStoreId();
                        $discounted_price = Mage::getResourceModel('catalogrule/rule')->getRulePrice(
                            Mage::app()->getLocale()->storeTimeStamp($store_id),
                            Mage::app()->getStore($store_id)->getWebsiteId(),
                            Mage::getSingleton('customer/session')->getCustomerGroupId(),
                            $_product->getId());
                        $specialprice = $discounted_price;

                    }*/
                    ?>
                    <?php if ($i++ % $_columnCount == 0): ?>

                <?php endif ?>
                    <div class="item col-lg-4 col-md-4 col-sm-4 respl-item haslabel" style="height:383px;">
						
													<div class="sale-item">
								<span class="txt-label">Sale</span>
							</div>
							
											
                        <div class="item-inner" style="height:100%;">
                            <div class="w-image-box">
                                <div class="item-image">
                                    <a href="<?php echo Mage::getUrl('product/index/index') . 'BN/'. $_product->Basic->ISBN; ?>" title="Ires mite rima" class="product-image">
<img id="product-collection-image-895" src="<?php  echo $_product->Basic->Image->IMG187;  ?>" alt="Ires mite rima" style="height:186px; widht:121px !important;"></a>
											
									                                </div>


                            </div>

                            <div class="item-info">
								
                                <div class="item-title">
                                    <a href="<?php echo Mage::getUrl('product/index/index') . 'BN/'. $_product->Basic->ISBN; ?>" title="<?php echo $_product->Basic->Title; ?>"><?php echo $_product->Basic->Title; ?></a>
                                </div>
							
								<div class="item-review">
                                        <div class="ratings">
        			            <div class="rating-box">
                <div class="rating" style="width:80%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://fiestic.com/review/product/list/id/895/category/72/'; return false;">2 Review(s)</a></span>
    </div>
                                </div>

                                <div class="item-price">
                                    

                        
    <div class="price-box">
                                                                <span class="regular-price">
                                            <span class="price">$<?php echo $_product->Basic->PubListPrice; ?></span>                                    </span>
                        
        </div>

                                </div>
                            </div>
							
							<div class="item-action">
																	<button title="Add to Cart" type="button" class="btn-pd btn-cart" onclick="setLocation('http://fiestic.com/books/electronic/ires-mite-rima.html?options=cart')">
										<span>
											<span>Add to Cart</span>
										</span>
									</button>
										

							
								<a style="display:none;" href="<?php echo Mage::getUrl('product/index/index') . 'BN/'. $_product->Basic->ISBN; ?>"></a>
																	<a data-toggle="tooltip" data-placement="top" title="" href="http://fiestic.com/wishlist/index/add/product/895/form_key/s2JZnjtb8azPH2mA/" class="btn-pd item-wishlist" data-original-title="Add to Wishlist" style="display: none;">
										<span>Add to Wishlist</span>
									</a>
										

																	<a data-toggle="tooltip" data-placement="top" title="" href="http://fiestic.com/catalog/product_compare/add/product/895/uenc/aHR0cDovL2ZpZXN0aWMuY29tL2Jvb2tzL2VsZWN0cm9uaWMuaHRtbA,,/form_key/s2JZnjtb8azPH2mA/" class="btn-pd item-compare" data-original-title="Add to Compare">
										<span>Add to Compare</span>
									</a>
																
							</div>

													

							
                        <a class="btn-pd sm_quickview_handler" data-toggle="tooltip" data-placement="top" title="" href="http://fiestic.com/quickview/index/view/path/books/electronic/ires-mite-rima.html" data-original-title="Quick View"><span>Quick View</span></a></div>
                    </div>
					<?php if($i % 2 == 0) : ?>
						<div class="clr2-item-plg"></div>
					<?php endif; ?>
					<?php if($i % 3 == 0) : ?>
						<div class="clr3-item-plg"></div>
					<?php endif; ?>
                    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>

                <?php endif ?>
                <?php endforeach ?>
            </div>
            <script
                type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        <?php endif; ?>

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
        <?php echo $this->getChildHtml('static-image-list') ?>
    </div>
    <?php if (!$this->getRequest()->isAjax()): ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
<script>
	jQuery(document).ready(function($) {
		$('.minimal-price-link').parent('.price-box').addClass('r-price-box');
	});	
</script>
<?php if ($this->helper('sm_shopby')->isAjaxEnabled() && !$this->getRequest()->isAjax()): ?>
    <script type="text/javascript">
        //<![CDATA[
        function pushState(data, link, replace) {
            var History = window.History;
            if (!History.enabled) {
                return false;
            }

            if (replace) {
                History.replaceState(data, document.title, link);
            } else {
                History.pushState(data, document.title, link);
            }
        }

        function handleEvent(el, event) {
            var url, fullUrl;
            if (typeof el === 'string') {
                url = el;
            } else if (el.tagName.toLowerCase() === 'a') {
                url = $(el).readAttribute('href');
            } else if (el.tagName.toLowerCase() === 'select') {
                url = $(el).getValue();
            }

            <?php // Add this to query string for full page caching systems ?>
            if (url.indexOf('?') != -1) {
                fullUrl = url + '&isLayerAjax=1';
            } else {
                fullUrl = url + '?isLayerAjax=1';
            }

            $('loading').show();
            $('ajax-errors').hide();

            pushState(null, url, false);

            new Ajax.Request(fullUrl, {
                method: 'get',
                onSuccess: function (transport) {
                    if (transport.responseJSON) {
                        $('catalog-listing').update(transport.responseJSON.listing);
                        $('layered-navigation').update(transport.responseJSON.layer);
                        pushState({
                            listing: transport.responseJSON.listing,
                            layer: transport.responseJSON.layer
                        }, url, true);
                        ajaxListener();
                    } else {
                        $('ajax-errors').show();
                    }
                    $('loading').hide();
                }
            });

            if (event) {
                event.preventDefault();
            }
        }
        function ajaxListener() {
            var els;
            els = $$('div.pager a').concat(
                $$('div.sorter a'),
                $$('div.pager select'),
                $$('div.sorter select'),
                $$('div.block-layered-nav a')
            );
            els.each(function (el) {
                if (el.tagName.toLowerCase() === 'a') {
                    $(el).observe('click', function (event) {
                        handleEvent(this, event);
                    });
                } else if (el.tagName.toLowerCase() === 'select') {
                    $(el).setAttribute('onchange', '');
                    $(el).observe('change', function (event) {
                        handleEvent(this, event);
                    });
                }
            });
        }
        document.observe("dom:loaded", function () {
            ajaxListener();

            (function (History) {
                if (!History.enabled) {
                    return false;
                }

                pushState({
                    listing: $('catalog-listing').innerHTML,
                    layer: $('layered-navigation').innerHTML
                }, document.location.href, true);

                // Bind to StateChange Event
                History.Adapter.bind(window, 'popstate', function (event) {
                    if (event.type == 'popstate') {
                        var State = History.getState();
                        $('catalog-listing').update(State.data.listing);
                        $('layered-navigation').update(State.data.layer);
                        ajaxListener();
                    }
                });
            })(window.History);
        });
        //]]>
    </script>
<?php endif; ?>

<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
