<?php
/*------------------------------------------------------------------------
 # SM Basic Products - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$list = $this->_getProducts();
$helper = Mage::helper('basicproducts/data');
//if (!empty($list)) {
    $uniqued = 'sm_basic_products_' . time() . rand();
	
	$nb_column1 = $this->_getConfig('nb_column1', 6);
	$nb_column2 = $this->_getConfig('nb_column2', 4);
	$nb_column3 = $this->_getConfig('nb_column3', 2);
	$nb_column4 = $this->_getConfig('nb_column4', 1);	

    $class_respl = 'bs-resp01-' . $this->_getConfig('nb_column1', 6) . ' bs-resp02-' . $this->_getConfig('nb_column2', 4) . ' bs-resp03-' . $this->_getConfig('nb_column3', 2) . ' bs-resp04-' . $this->_getConfig('nb_column4', 1);

    ?>
<div class="block basic-slide-block-v2">
    <?php if ($this->_getConfig('pretext') != null) { ?>
        <div class="bs-pretext">
            <?php echo $this->_getConfig('pretext'); ?>
        </div>
    <?php } ?>

    <?php //if ($this->_getConfig('title')) { ?>
        <div class="block-title">
            <span><?php echo 'BEST SELLERS ' ?></span>
        </div>
   <!-- <?php //}else { 
		//if ($this->_getConfig('basicproducts_title_text')) { ?>
			<div class="block-title">
				<span><?php //echo $this->_getConfig('basicproducts_title_text', 'Basic Products Title'); ?></span>
			</div>		
		<?php //}
	//} ?>-->
	
	<div class="slide-basic-v2">
		<?php  $j = 0;
                for($y=0; $y < 5; $y++){
		//foreach ($list as $_product) {
			$j++;

			$now = date("Y-m-d");
			//$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
			//$newsTo = substr($_product->getData('news_to_date'), 0, 10);			
			?>	
			
            
            
            
            
            <?php //------------------------------------------------------->>>>>>>>  ?>
            <div class="owl-item active" style="width: 210px; margin-right: 0px;"><div class="item item-basic-v2 respl-item haslabel">
									<div class="sale-item customlabel" style="height: 28px;
    width: 51px;
    position: absolute;
    margin-left: -62px;">
<img src="<?php echo Mage::getBaseUrl('media').'sm/fiestic_sale.png'?>" style="height:28px; width:51px;">						
<!--<span>Sale</span>-->
					</div>
								
			
									<div class="new-item " style="height: 28px;
    width: 51px;
    position: absolute;
    margin-left: 2px;">
                                                                            <img src="<?php echo Mage::getBaseUrl('media').'sm/fiestic_new.png'?>" style="height:28px; width:51px;">
						
					</div>
							
				<div class="item-inner">
											<div class="w-image-box">
							<div class="image-w">
								<div class="item-image">
									<a href="http://127.0.0.1/fiestic2/index.php/cori-miren-masem.html" title="Cori miren mase">
										<img src="http://127.0.0.1/fiestic2/media/catalog/product/resized/128x197/27aae3a567691a4df1106d8229e40130/15_1.jpg" title="Cori miren mase" alt="Cori miren mase">
									</a>
								</div>
							</div>
						</div>						
											
					
					<div class="item-info">
					
						
													<div class="item-title">
								<a href="http://127.0.0.1/fiestic2/index.php/cori-miren-masem.html" title="Cori miren mase">
									Cori miren mase								</a>
							</div>
								

		
					
												
																	

													<div class="item-price">
																	

                        
    <div class="price-box">
                                            
                    <p class="old-price">
                <span class="price-label">Regular Price:</span>
                <span class="price">
                    $5,568.00                </span>
            </p>

                            <p class="special-price">
                    <span class="price-label">Special Price</span>
                <span class="price">
                    $0.00                </span>
                </p>
                    
    
        </div>

														
							</div>
												
													<div class="item-action">
								
																										<button type="button" data-toggle="tooltip" data-placement="top" title="" class="btn-pd btn-cart" onclick="setLocation('http://127.0.0.1/fiestic2/index.php/checkout/cart/add/uenc/aHR0cDovLzEyNy4wLjAuMS9maWVzdGljMi8,/product/900/form_key/jv9r9Cx6FpHCxrdu/')" data-original-title="Buy">
															<span><span>Buy</span></span>
									</button>
									
																	<a data-toggle="tooltip" data-placement="top" title="" href="http://127.0.0.1/fiestic2/index.php/wishlist/index/add/product/900/form_key/jv9r9Cx6FpHCxrdu/" class="btn-pd item-wishlist" data-original-title="Add to Wishlist" style="display: none;">
										<span>Add to Wishlist</span>
									</a>
								
											
							</div>
						
											</div> 
					<a style="display:none;" href="http://127.0.0.1/fiestic2/index.php/cori-miren-masem.html" title="Cori miren mase"> </a>

					
													<a data-toggle="tooltip" data-placement="top" title="" href="http://127.0.0.1/fiestic2/index.php/catalog/product_compare/add/product/900/uenc/aHR0cDovLzEyNy4wLjAuMS9maWVzdGljMi8,/form_key/jv9r9Cx6FpHCxrdu/" class="btn-pd item-compare" data-original-title="Add to Compare" style="display: none;">
								<span>Add to Compare</span>
							</a>
															
						
					
				<a class="btn-pd sm_quickview_handler" data-toggle="tooltip" data-placement="top" title="" href="http://127.0.0.1/fiestic2/index.php/quickview/index/view/path/cori-miren-masem.html" data-original-title="Quick View"><span>Quick View</span></a></div>
			</div></div>
            
            
             <?php //------------------------------------------------------->>>>>>>>  ?>
            
		
		<?php } ?>
	</div>
	
	<script>
			jQuery(document).ready(function($) {
				var owl_basic = $(".slide-basic-v2");
				owl_basic.owlCarousel({

					autoplayHoverPause: true,
					autoplaySpeed: 300,
					paginationSpeed : 400,
					autoPlay:false,
					dots: false,
					nav: true,
					navClass: ['owl-prev', 'owl-next'],
					navText: ['&nbsp;', '&nbsp;'],				

					responsive: {
						0: {
							items:1						
							},
						480: {
							items:<?php echo $nb_column4;?>							
							},
						768: {
							items:<?php echo $nb_column3;?>							
							},
						992: {
							items:<?php echo $nb_column2;?>							
						},
						1200: {
							items:<?php echo $nb_column1;?>							
							}
					}
					
				});	 
			});	
	</script>
	
</div>

<?php if ($this->_getConfig('posttext') != null) { ?>
	<div class="bs-posttext">
		<?php echo $this->_getConfig('posttext'); ?>
	</div>
<?php } ?>


<?php
//} else {
  //  echo 'Has no content to show!';
//}?>
