<?php
/*------------------------------------------------------------------------
 # SM Basic Products - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
$list = $this->_getProducts();
$helper = Mage::helper('basicproducts/data');
if (!empty($list)) {
    $uniqued = 'sm_basic_products_' . time() . rand();
	
	$nb_column1 = $this->_getConfig('nb_column1', 6);
	$nb_column2 = $this->_getConfig('nb_column2', 4);
	$nb_column3 = $this->_getConfig('nb_column3', 2);
	$nb_column4 = $this->_getConfig('nb_column4', 1);	

    $class_respl = 'bs-resp01-' . $this->_getConfig('nb_column1', 6) . ' bs-resp02-' . $this->_getConfig('nb_column2', 4) . ' bs-resp03-' . $this->_getConfig('nb_column3', 2) . ' bs-resp04-' . $this->_getConfig('nb_column4', 1);

    ?>
<div class="block basic-slide-block-v2">
    <?php if ($this->_getConfig('pretext') != null) { ?>
        <div class="bs-pretext">
            <?php echo $this->_getConfig('pretext'); ?>
        </div>
    <?php } ?>

    <?php if ($this->_getConfig('title')) { ?>
        <div class="block-title">
            <span><?php echo $this->_getConfig('title', 'Basic Products Title'); ?></span>
        </div>
    <?php }else { 
		if ($this->_getConfig('basicproducts_title_text')) { ?>
			<div class="block-title">
				<span><?php echo $this->_getConfig('basicproducts_title_text', 'Basic Products Title'); ?></span>
			</div>		
		<?php }
	} ?>
	
	<div class="slide-basic-v2">
		<?php  $j = 0;
		foreach ($list as $_product) {
			$j++;

			$now = date("Y-m-d");
			$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
			$newsTo = substr($_product->getData('news_to_date'), 0, 10);			
			?>	
			
			<div class="item item-basic-v2 respl-item<?php echo ( $_product->getSpecialPrice() || $newsFrom != "" && $now >= $newsFrom && ($now <= $newsTo || $newsTo == "") )? " haslabel":"";?>">
				<?php if ( $_product->getSpecialPrice() ){ ?>
					<div class="sale-item <?php echo ($newsFrom != "" && $now >= $newsFrom && ($now <= $newsTo || $newsTo == ""))? "label2":""; ?>">
						<span><?php echo $this->__('Sale'); ?></span>
					</div>
				<?php }?>
				
			
				<?php if ($newsFrom != "" && $now >= $newsFrom && ($now <= $newsTo || $newsTo == "")) { ?>
					<div class="new-item <?php echo ( $_product->getSpecialPrice() )? "label2":""; ?>">
						<span class="txt-label"><?php echo $this->__('New') ?></span>
					</div>
				<?php } ?>			
				<div class="item-inner">
					<?php if ($_product->_image) { ?>
						<div class="w-image-box">
							<div class="image-w">
								<div class="item-image">
									<a href="<?php echo $_product->link ?>"
									   title="<?php echo $_product->title; ?>"
										<?php echo $helper->parseTarget($this->_getConfig('product_links_target')); ?>
										>
										<img src="<?php echo $_product->_image; ?>"
											 title="<?php echo $_product->title; ?>"
											 alt="<?php echo $_product->title; ?>"
											>
									</a>
								</div>
							</div>
						</div>						
					<?php } ?>						
					
					<div class="item-info">
					
						
						<?php if( (int)$this->_getConfig('product_title_display',1) ) { ?>
							<div class="item-title">
								<a href="<?php echo $_product->link;?>" title="<?php echo $_product->title; ?>"
									<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
									>
									<?php echo $helper->truncate($_product->title,$this->_getConfig('product_title_maxlength'));?>
								</a>
							</div>
						<?php } ?>		

		
					
						<?php if ( (int)$this->_getConfig('product_reviews_count', 1) ) { ?>
							<div class="item-review">
								<?php echo $this->getReviewsSummaryHtml($_product, 'short', true); ?>
							</div>
						<?php } ?>
						
						<?php if ((int)$this->_getConfig('product_description_display', 1) && $helper->_trimEncode($_product->_description) != '') { ?>
							<div class="des-content">
								<?php echo $_product->_description; ?>
							</div>
						<?php } ?>											

						<?php if ((int)$this->_getConfig('product_price_display', 1) || (int)$this->_getConfig('product_addcart_display', 1)) { ?>
							<div class="item-price">
								<?php if ((int)$this->_getConfig('product_price_display', 1)) { ?>
									<?php echo $this->getPriceHtml($_product, true); ?>
								<?php } ?>
						
							</div>
						<?php } ?>
						
						<?php if ((int)$this->_getConfig('product_addcompare_display', 1) || (int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcart_display', 1)) { ?>
							<div class="item-action">
								
								<?php if ((int)$this->_getConfig('product_addcart_display', 1)) : ?>
									<?php if ($_product->isSaleable()): ?>
									<button type="button" data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Buy') ?>"
																class="btn-pd btn-cart"
																onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
															<span><span><?php echo $this->__('Buy') ?></span></span>
									</button>
									<?php else: ?>
									<p class="availability out-of-stock">
										<span><?php echo $this->__('Out of stock') ?></span>
									</p>
									<?php endif;
								endif; ?>

								<?php if ($this->helper('wishlist')->isAllow() && (int)$this->_getConfig('product_addwishlist_display', 1)) : ?>
									<a data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Add to Wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"  class="btn-pd item-wishlist">
										<span><?php echo $this->__('Add to Wishlist') ?></span>
									</a>
								<?php endif; ?>

											
							</div>
						<?php } ?>

						<?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
							<div class="deal-detail">
								<a href="<?php echo $_product->link ?>"
									title="<?php echo $_product->title; ?>"
									<?php echo $helper->parseTarget($this->_getConfig('product_links_target'));?>
									>
									<?php echo $this->_getConfig('product_readmore_text','Details'); ?>
								</a>
							</div>
						<?php } ?>
					</div> 
					<a style="display:none;" href="<?php echo $_product->link;?>" title="<?php echo $_product->title; ?>" > </a>

					<?php if ((int)$this->_getConfig('product_addcompare_display', 1)) {?>

						<?php if ($_compareUrl = $this->getAddToCompareUrl($_product) && (int)$this->_getConfig('product_addcompare_display', 1)): ?>
							<a data-toggle="tooltip" data-placement="top" title="<?php echo $this->__('Add to Compare') ?>" href="<?php echo $this->getAddToCompareUrl($_product) ?>" class="btn-pd item-compare">
								<span><?php echo $this->__('Add to Compare') ?></span>
							</a>
						<?php endif; ?>
									
					<?php } ?>	
					
				</div>
			</div>
		
		<?php } ?>
	</div>
	
	<script>
			jQuery(document).ready(function($) {
				var owl_basic = $(".slide-basic-v2");
				owl_basic.owlCarousel({

					autoplayHoverPause: true,
					autoplaySpeed: 300,
					paginationSpeed : 400,
					autoPlay:false,
					dots: false,
					nav: true,
					navClass: ['owl-prev', 'owl-next'],
					navText: ['&nbsp;', '&nbsp;'],				

					responsive: {
						0: {
							items:1						
							},
						480: {
							items:<?php echo $nb_column4;?>							
							},
						768: {
							items:<?php echo $nb_column3;?>							
							},
						992: {
							items:<?php echo $nb_column2;?>							
						},
						1200: {
							items:<?php echo $nb_column1;?>							
							}
					}
					
				});	 
			});	
	</script>
	
</div>

<?php if ($this->_getConfig('posttext') != null) { ?>
	<div class="bs-posttext">
		<?php echo $this->_getConfig('posttext'); ?>
	</div>
<?php } ?>


<?php
} else {
    echo 'Has no content to show!';
}?>