<?php
/*------------------------------------------------------------------------
 # SM Deal - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<?php 

$p_images=array();
$p_images[]=Mage::getBaseUrl('media').'sm/carnival_de_paris.png';
$p_images[]=Mage::getBaseUrl('media').'sm/shutterstock.png';
$p_images[]=Mage::getBaseUrl('media').'sm/carnival_de_paris.png';
$p_images[]=Mage::getBaseUrl('media').'sm/shutterstock.png';
$p_images[]=Mage::getBaseUrl('media').'sm/carnival_de_paris.png';




$list = $this->_getProducts();
$helper = Mage::helper('deal/data');
//if (!empty($list)) {
	$uniqued = 'sm_deal_' . time() . rand();
	
	$class_suffix = $this->_getConfig('class_suffix', '');
	
	$static_id_left = $this->_getConfig('static_id_left', '');
	$static_id_right = $this->_getConfig('static_id_right', '');

	$nb_column1 = $this->_getConfig('nb_column1', 6);
	$nb_column2 = $this->_getConfig('nb_column2', 4);
	$nb_column3 = $this->_getConfig('nb_column3', 2);
	$nb_column4 = $this->_getConfig('nb_column4', 1);
	
	$showtime = $this->_getConfig('showtime', 1);	
	
	$class_slide = 'col-lg-12';
	$class_static = 'col-lg-4 col-md-4 col-sm-12';
	if($static_id_left && $static_id_right) {
		$class_slide = 'col-lg-6 col-md-6 col-sm-12';
		$class_static = 'col-lg-3 col-md-3 col-sm-12';
	}
	if($static_id_left || $static_id_right) {
		$class_slide = 'col-lg-8 col-md-8 col-sm-12';
	}
	
?>

<div class="deal-wrapper-banner deal-wrapper-banner-notime block <?php echo $class_suffix; ?>">
	<div class="row">
		<?php if($static_id_left && $static_id_left != ''):?>
			<div class="static-l <?php echo $class_static; ?>">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($static_id_left)->toHtml();?>
			</div>
		<?php endif; ?>
		<div class="deal-wrapper block <?php echo $class_slide; ?>">
			<div class="deal-wrapper-inner">
			<!--<?php// if( $this->_getConfig('deal_title_text') ){ ?>-->
				<div class="block-title">
					<span><?php echo 'FEATURED PRODUCTS'; ?></span>
				</div>
			<!--<?php //} ?>-->


			<div id="<?php echo $uniqued; ?>" class="sm-deal-wrap">
				
				
				<?php if ( $this->_getConfig('pretext') != null ) { ?>
					<div class="deal-pretext">
						<?php echo $this->_getConfig('pretext'); ?>
					</div>
				<?php } ?>
				<div class="w-deal-res deal-home-df">
					<div class="overflow-owl-slider">
						<div class="rw-margin">
						<div class="slider-deal-slidebar">
							<?php 
							$j = 0;
							$_limit = (int)$this->_getConfig('product_limitation', 5);
							for($i=0; $i<5; $i++){
//foreach ($list as $_product) {
                                                             ?>
                                                    
                                                    <div class="owl-item active" style="width: 285.5px; margin-right: 0px;"><div class="item item-deal respl-item">
									<div class="item-inner">
										
																					<div class="w-image-box">
												<div class="image-w">
													<div class="item-image">
														<a href="#" title="Kera more poza ">
															<img src="<?php echo $p_images[$i]; ?>" title="Kera more poza " alt="Kera more poza ">
														</a>
													</div>
				
												</div>

											</div>
																				
										<div class="item-info">
										
											
																							<div class="item-title">
													<a href="http://127.0.0.1/fiestic2/index.php/kera-more-poza.html" title="Kera more poza ">
														Kera more poza 													</a>
												</div>
													

							
										
																							<div class="item-review">
													    <div class="ratings">
        			            <div class="rating-box">
                <div class="rating" style="width:87%"></div>
            </div>
                <span class="amount"><a href="#" onclick="var t = opener ? opener.window : window; t.location.href='http://127.0.0.1/fiestic2/index.php/review/product/list/id/909/'; return false;">2 Review(s)</a></span>
    </div>
												</div>
																						
																							<div class="des-content">
													Fusce porttitor at ante eu egestas. Morbi vulputate diam at nibh imperdiet pretium. Nulla euismod, ...												</div>
																						

																							<div class="item-price">
																											

                        
    <div class="price-box">
                                            
                    <p class="old-price">
                <span class="price-label">Regular Price:</span>
                <span class="price">
                    $565.00                </span>
            </p>

                            <p class="special-price">
                    <span class="price-label">Special Price</span>
                <span class="price">
                    $0.00                </span>
                </p>
                    
    
        </div>

																								
												</div>
																						
																							<div class="item-action">
													
																																									<button type="button" title="Buy" class="btn-pd btn-cart" onclick="">
																				<span><span>Buy</span></span>
														</button>
														
																											<a data-toggle="tooltip" data-placement="top" title="" href="#" class="btn-pd item-wishlist" data-original-title="Add to Wishlist">
															<span>Add to Wishlist</span>
														</a>
													
													
																													<a data-toggle="tooltip" data-placement="top" title="" href="#" class="btn-pd item-compare" data-original-title="Add to Compare">
																<span>Add to Compare</span>
															</a>
																															
																									
												</div>
											
																					</div> 
										<a style="display:none;" href="#" title="Kera more poza "> </a>


										
									<a class="btn-pd sm_quickview_handler" data-toggle="tooltip" data-placement="top" title="" href="#" data-original-title="Quick View"><span>Quick View</span></a></div>
								</div></div>
                                                    
                                                    
                                                    
                                                    
                                                            <?php } ?>
						</div>
						</div>
					</div>
				</div>
			</div>
			</div>	
		</div>
		<?php if($static_id_right && $static_id_right != ''):?>
			<div class="static-r <?php echo $class_static; ?>">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId($static_id_right)->toHtml();?>
			</div>
		<?php endif; ?>	
	</div>
</div>
<script>
		jQuery(document).ready(function($) {
			var owl_deal_slidebar = $("#<?php echo $uniqued; ?> .slider-deal-slidebar");
			owl_deal_slidebar.owlCarousel({

				autoplayHoverPause: true,
				autoplaySpeed: 300,
				paginationSpeed : 400,
				autoPlay:false,
				dots: false,
				nav: true,
				navClass: ['owl-prev', 'owl-next'],
				navText: ['', ''],				

				responsive: {
					0: {
						items:1
						},
					480: {
						items:<?php echo $nb_column4;?>							
						},
					768: {
						items:<?php echo $nb_column3;?>							
						},
					992: {
						items:<?php echo $nb_column2;?>							
					},
					1200: {
						items:<?php echo $nb_column1;?>							
						}
				}
				
			});	 
		});	
</script>
<?php if ($this->_getConfig('posttext') != null) { ?>
	<div class="deal-posttext"><?php echo $this->_getConfig('posttext'); ?></div>
<?php } ?>
	
<!--<?php// } else { echo $this->__('Has no content to show!'); }; ?>-->