<?php
/*------------------------------------------------------------------------
 # SM Deal - Version 1.0.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/?>

<?php
$list = $this->getList();
$shop = Mage::getModel('ingram/shop');
 // echo "<pre>";print_r($data);die;
 $i=0;
 $p_names=array();
 $p_images=array();
 $p_ean=array();
 $ingram_price=array();
 $p_price=array();
 $p_href=array();
 $desc = array();
 $uniq = array();
 $pub = array();
foreach($list as $dat){
    $p_href[]= $shop->getProductUrl($dat);
    $p_ean[]= $shop->getProductUniq($dat);
    $p_names[]= $shop->getProductName($dat);
    $p_images[]=$shop->getProductImage($dat);
    $ingram_price[]=$shop->getProductPrice($dat);
    $p_price[]=$shop->getProductMRP($dat);
    $pub[] = $shop->getProductPublisher($dat);
    $desc[] = $shop->getProductShortDesc($dat);
    $uniq[] = $shop->getProductUniq($dat);
    
}

$helper = Mage::helper('deal/data');
	$class_suffix = '';
	$class_slide = 'col-lg-12 col-md-12 col-sm-12';
	$uniqued = time();
?>

<div class="deal-wrapper-banner deal-wrapper-banner-notime block <?php echo $class_suffix; ?>">
	<div class="row">
		<?php 
		$static_id_left = 'b-img1-homepage2';
		$class_static = 'col-lg-4 col-md-4 col-sm-12';
		//if($static_id_left && $static_id_left != ''):?>
			<!--<div class="static-l <?php echo $class_static; ?>">
				<?php// echo $this->getLayout()->createBlock('cms/block')->setBlockId($static_id_left)->toHtml();?>
			</div>-->
		<?php// endif; ?>
		<div class="deal-wrapper block <?php echo $class_slide; ?>">
			<div class="deal-wrapper-inner">
				<div class="block-title">
					<span><?php echo $this->getTitle(); ?></span>
				</div>


			<div id="<?php echo $uniqued; ?>" class="sm-deal-wrap">
				<div class="w-deal-res deal-home-df">
					<div class="overflow-owl-slider">
						<div class="rw-margin">
						<div class="slider-deal-slidebar">
							<?php  for($i=0; $i<sizeof($p_href); $i++){ ?>
                                                    
                               <div class="owl-item active" style="width: 240px; margin-right: 0px;"><div class="item item-deal respl-item">
									<div class="item-inner">
										<div class="w-image-box">
												<div class="image-w">
													<div class="item-image">
														<a href="<?php echo $p_href[$i]; ?>" title="<?php echo $p_names[$i]; ?>">
															<input type="hidden" name="unique_code" value="<?php echo $uniq[$i]; ?>" id="unique_code" class="unique_code"> 
															<img src="<?php echo $p_images[$i]; ?>" title="<?php echo $p_names[$i]; ?>" alt="<?php echo $p_names[$i]; ?>">
														</a>
													</div>
				
												</div>

											</div>
																				
										<div class="item-info">
											<div class="item-title">
													<a href="<?php echo $p_href[$i];?>" title="<?php echo $p_names[$i]; ?>">
														<?php echo $p_names[$i]; ?>												</a>
												</div>
										 															
												<div class="des-content">
												Publisher: <?php echo $pub[$i]; ?>
												<br/>
												<?php echo $desc[$i]; ?>
												</div>


												<div class="item-price">
																											

                        
												    <div class="price-box">
												                                            
												                    <p class="old-price">
												                <span class="price-label">Regular Price:</span>
												                <span class="price">
												                    $<?php echo $p_price[$i]; ?>                </span>
												            </p>

												                            <p class="special-price">
												                    <span class="price-label">Special Price</span>
												                <span class="price">
												                    $<?php echo $ingram_price[$i]; ?>             </span>
												                </p>
												                    
												    
												        </div>

																								
												</div>
																						
													<div class="item-action">
															<button type="button" title="Buy" class="btn-pd btn-cart" onclick="window.location.href='<?php echo $p_href[$i];?>';">
																	<span><span>Buy</span></span>
															</button>															
																										
													</div>
																				
												</div> 
										<a style="display:none;" href="#" title="<?php echo $p_names[$i];?>"> </a>


										
									<!-- <a class="btn-pd sm_quickview_handler" data-toggle="tooltip" data-placement="top" title="" href="#" data-original-title="Quick View"><span>Quick View</span></a> -->
									</div>
								</div></div>
                                                    
                                                    
                                                    
                                                    
                                                            <?php } ?>
						</div>
						</div>
					</div>
				</div>
			</div>
			</div>	
		</div>
	</div>
</div>
<script>
		jQuery(document).ready(function($) {
			var owl_deal_slidebar = $("#<?php echo $uniqued; ?> .slider-deal-slidebar");
			owl_deal_slidebar.owlCarousel({

				autoplayHoverPause: true,
				autoplaySpeed: 300,
				paginationSpeed : 400,
				autoPlay:false,
				dots: false,
				nav: true,
				navClass: ['owl-prev', 'owl-next'],
				navText: ['', ''],				

				responsive: {
					0: {
						items:1
						},
					480: {
						items:2							
						},
					768: {
						items:2							
						},
					992: {
						items:2							
					},
					1200: {
						items:2							
						}

				}
				
			});	 
		});	
</script>