<?php
/*------------------------------------------------------------------------
 # SM Shop By - Version 1.0
 # Copyright (c) 2014 YouTech Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: YouTech Company
 # Websites: http://www.magentech.com
-------------------------------------------------------------------------*/
?>
<?php
echo 'abcxyz';die;
$_productCollection=Mage::registry('ingram_products');
echo '<pre>';print_r($_productCollection);die;
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_productCollection->Book->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <?php if (!$this->getRequest()->isAjax()): ?>
        <div id="ajax-errors" style="display: none;">
            <ul class="messages">
                <li class="error-msg">
                    <ul>
                        <li><span><?php echo $this->__('An error occurred, please try again later.'); ?></span></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div id="loading" style="display: none; margin-bottom: 10px; text-align: center;">
            <img class="v-middle" alt="" src="<?php echo $this->getSkinUrl('images/loading-qv.gif'); ?>">
        </div>

<div id="catalog-listing">
    <?php endif; ?>
    <div class="category-products">
        <?php //echo $this->getToolbarHtml() ?>

        <?php // Grid Mode ?>

        <?php $_collectionSize = $_productCollection->Book->count() ?>
        <?php //$_columnCount = $this->getColumnCount(); ?>
            <div class="products-grid row">
                <?php $i = 0;
                foreach ($_productCollection->Book as $_product):
                    //$id_product = Mage::getModel('catalog/product')->load($_product->getId());
                    //$count_input_qty++;
                    $now = date("Y-m-d");
                    //$newsFrom = substr($_product->getData('news_from_date'), 0, 10);
                    //$newsTo = substr($_product->getData('news_to_date'), 0, 10);

                    //$specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice();
                    //echo $specialprice . '-hau<br/>';
                    //$price = Mage::getModel('catalog/product')->load($_product->getId())->getPrice();
                    /*if ($specialprice == '') {
                        $store_id = Mage::app()->getStore()->getStoreId();
                        $discounted_price = Mage::getResourceModel('catalogrule/rule')->getRulePrice(
                            Mage::app()->getLocale()->storeTimeStamp($store_id),
                            Mage::app()->getStore($store_id)->getWebsiteId(),
                            Mage::getSingleton('customer/session')->getCustomerGroupId(),
                            $_product->getId());
                        $specialprice = $discounted_price;

                    }*/
                    ?>
                    <?php if ($i++ % $_columnCount == 0): ?>

                <?php endif ?>
                    <div class="item col-lg-4 col-md-4 col-sm-4 respl-item haslabel">
						
													<div class="sale-item">
								<span class="txt-label">Sale</span>
							</div>
							
											
                        <div class="item-inner">
                            <div class="w-image-box">
                                <div class="item-image">
                                    <a class="product-image" title="Kera more poza " href="http://fiestic.com/kera-more-poza.html">
									   <img alt="Kera more poza " src="http://fiestic.com/media/catalog/product/cache/1/small_image/109x168/9df78eab33525d08d6e5fb8d27136e95/1/3/13_1_1.jpg" id="product-collection-image-909"></a>
											
									                                </div>


                            </div>

                            <div class="item-info">
								
                                <div class="item-title">
                                    <a title="Kera more poza " href="http://fiestic.com/kera-more-poza.html">Kera more poza </a>
                                </div>
							
								<div class="item-review">
                                        <div class="ratings">
        			            <div class="rating-box">
                <div style="width:87%" class="rating"></div>
            </div>
                <span class="amount"><a onclick="var t = opener ? opener.window : window; t.location.href='http://fiestic.com/review/product/list/id/909/'; return false;" href="#">2 Review(s)</a></span>
    </div>
                                </div>

                                <div class="item-price">
                                    

                        
    <div class="price-box">
                                            
                    <p class="old-price">
                <span class="price-label">Regular Price:</span>
                <span class="price">
                    $565.00                </span>
            </p>

                            <p class="special-price">
                    <span class="price-label">Special Price</span>
                <span class="price">
                    $500.00                </span>
                </p>
                    
    
        </div>

                                </div>
                            </div>
							
							<div class="item-action">
																	<button onclick="setLocation('http://fiestic.com/checkout/cart/add/uenc/aHR0cDovL2ZpZXN0aWMuY29tL2NhdGFsb2dzZWFyY2gvcmVzdWx0L2luZGV4Lz9jYXQ9MTMwJnE9S2VyYSttb3JlK3BvemErJmlzTGF5ZXJBamF4PTE,/product/909/form_key/SHSlVkdJp1YeUJGD/')" class="btn-pd btn-cart" type="button" title="Add to Cart">
										<span>
											<span>Add to Cart</span>
										</span>
									</button>
										

							
								<a href="http://fiestic.com/kera-more-poza.html" style="display:none;"></a>
																	<a class="btn-pd item-wishlist" href="http://fiestic.com/wishlist/index/add/product/909/form_key/SHSlVkdJp1YeUJGD/" title="" data-placement="top" data-toggle="tooltip" data-original-title="Add to Wishlist">
										<span>Add to Wishlist</span>
									</a>
										

																	<a class="btn-pd item-compare" href="http://fiestic.com/catalog/product_compare/add/product/909/uenc/aHR0cDovL2ZpZXN0aWMuY29tL2NhdGFsb2dzZWFyY2gvcmVzdWx0L2luZGV4Lz9jYXQ9MTMwJnE9S2VyYSttb3JlK3BvemErJmlzTGF5ZXJBamF4PTE,/form_key/SHSlVkdJp1YeUJGD/" title="" data-placement="top" data-toggle="tooltip" data-original-title="Add to Compare">
										<span>Add to Compare</span>
									</a>
																
							</div>

													

							
                        <a href="http://fiestic.com/quickview/index/view/path/kera-more-poza.html" title="" data-placement="top" data-toggle="tooltip" class="btn-pd sm_quickview_handler" data-original-title="Quick View" style="display: none;"><span>Quick View</span></a></div>
                    </div>
					<?php if($i % 2 == 0) : ?>
						<div class="clr2-item-plg"></div>
					<?php endif; ?>
					<?php if($i % 3 == 0) : ?>
						<div class="clr3-item-plg"></div>
					<?php endif; ?>
                    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>

                <?php endif ?>
                <?php endforeach ?>
            </div>
            <script
                type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
        
        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
        <?php echo $this->getChildHtml('static-image-list') ?>
    </div>
    <?php if (!$this->getRequest()->isAjax()): ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
<script>
	jQuery(document).ready(function($) {
		$('.minimal-price-link').parent('.price-box').addClass('r-price-box');
	});	
</script>
<?php if ($this->helper('sm_shopby')->isAjaxEnabled() && !$this->getRequest()->isAjax()): ?>
    <script type="text/javascript">
        //<![CDATA[
        function pushState(data, link, replace) {
            var History = window.History;
            if (!History.enabled) {
                return false;
            }

            if (replace) {
                History.replaceState(data, document.title, link);
            } else {
                History.pushState(data, document.title, link);
            }
        }

        function handleEvent(el, event) {
            var url, fullUrl;
            if (typeof el === 'string') {
                url = el;
            } else if (el.tagName.toLowerCase() === 'a') {
                url = $(el).readAttribute('href');
            } else if (el.tagName.toLowerCase() === 'select') {
                url = $(el).getValue();
            }

            <?php // Add this to query string for full page caching systems ?>
            if (url.indexOf('?') != -1) {
                fullUrl = url + '&isLayerAjax=1';
            } else {
                fullUrl = url + '?isLayerAjax=1';
            }

            $('loading').show();
            $('ajax-errors').hide();

            pushState(null, url, false);

            new Ajax.Request(fullUrl, {
                method: 'get',
                onSuccess: function (transport) {
                    if (transport.responseJSON) {
                        $('catalog-listing').update(transport.responseJSON.listing);
                        $('layered-navigation').update(transport.responseJSON.layer);
                        pushState({
                            listing: transport.responseJSON.listing,
                            layer: transport.responseJSON.layer
                        }, url, true);
                        ajaxListener();
                    } else {
                        $('ajax-errors').show();
                    }
                    $('loading').hide();
                }
            });

            if (event) {
                event.preventDefault();
            }
        }
        function ajaxListener() {
            var els;
            els = $$('div.pager a').concat(
                $$('div.sorter a'),
                $$('div.pager select'),
                $$('div.sorter select'),
                $$('div.block-layered-nav a')
            );
            els.each(function (el) {
                if (el.tagName.toLowerCase() === 'a') {
                    $(el).observe('click', function (event) {
                        handleEvent(this, event);
                    });
                } else if (el.tagName.toLowerCase() === 'select') {
                    $(el).setAttribute('onchange', '');
                    $(el).observe('change', function (event) {
                        handleEvent(this, event);
                    });
                }
            });
        }
        document.observe("dom:loaded", function () {
            ajaxListener();

            (function (History) {
                if (!History.enabled) {
                    return false;
                }

                pushState({
                    listing: $('catalog-listing').innerHTML,
                    layer: $('layered-navigation').innerHTML
                }, document.location.href, true);

                // Bind to StateChange Event
                History.Adapter.bind(window, 'popstate', function (event) {
                    if (event.type == 'popstate') {
                        var State = History.getState();
                        $('catalog-listing').update(State.data.listing);
                        $('layered-navigation').update(State.data.layer);
                        ajaxListener();
                    }
                });
            })(window.History);
        });
        //]]>
    </script>
<?php endif; ?>

<?php
// Provides a block where additional page components may be attached, primarily good for in-page JavaScript
if ($this->getChild('after')) {
    $_afterChildren = $this->getChild('after')->getSortedChildren();
    foreach ($_afterChildren as $_afterChildName) {
        $_afterChild = $this->getChild('after')->getChild($_afterChildName);
        //set product collection on after blocks
        $_afterChild->setProductCollection($_productCollection);
        echo $_afterChild->toHtml();
    }
}
?>
