<style type="text/css">
    .menu-container{color:black;}
    .menu_img{max-height:30px; max-width:px;}
    .menu_subcategory{padding-top: 20px; padding-left: 10px;}
    
    
    .selectParent{
    width:22px;
    /*overflow:hidden;*/
   
   
}

.selectParent select{
    width:22px;
    height:25px;
    -webkit-appearance: none;
    -moz-appearance: none;
    appearance: none;
    padding: 2px 2px 2px 20px;
    border: none;
     background: transparent url("http://cdn1.iconfinder.com/data/icons/cc_mono_icon_set/blacks/16x16/br_down.png") no-repeat left center;
   
}
   
.fa-user:before{
    font-size:16px;
}
</style>
<?php global $var_yttheme; ?>
<?php $identifier = Mage::getSingleton('cms/page')->getIdentifier();?>
<div class="header-default header-v2">
	<div class="yt-header-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 logo-wrapper">
					<div class="logo-wrapper-inner">
						<h1>
							<a title="<?php echo $this->getLogoAlt() ?>" href="<?php echo $this->getUrl('') ?>">
								<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
							</a>

							<?php if ($identifier !="home-v2") {?>
							<!--<div class="btn-menu-destop"><i class="fa fa-angle-down"></i></div>-->
							<?php } ?>
						</h1>
						
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 wrap-menu-mobi">
					<div id="yt-responsivemenu" class="yt-responsivemenu">
						<?php echo $this->getChildHtml('mobiMenu'); ?>
					</div>
				</div>
				<div class="col-lg-6 col-md-9 col-sm-6 right-wrapper">
					<!--<div class="wrap-search-mobile">
						<a class="btn-search-mobile icon-search" href="javascript:void(0)" title="<?php echo $this->__('Search')?>"><i class="fa fa-search"></i></a>
						<script>
							jQuery(document).ready(function($){
								$( ".btn-search-mobile" ).click(function() {
									$('.search-pro').toggleClass('show')
									$(this).toggleClass('active')
								});
							});
						</script>
					</div>-->
					<?php echo $this->getChildHtml('currency'); ?>
					<?php echo $this->getChildHtml('store_language') ?>
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                    
					

					<div class="mini-cart-header">
						<?php echo $this->getChildHtml('mini-cartpro') ?>
					</div>
                                    
                                    <div class="top-links-action">

						<div class="block-action-header top-link-account login-link" style="float:right;">
							<ul>
								<?php if(!$this->helper('customer')->isLoggedIn()){?>
								<li>
									<a class="login-btn" data-toggle="modal" data-target="#modal-login" title="<?php echo $this->__('Login')?>"><i class="fa fa-user" style="color:white;"></i><?php echo $this->__('')?></a>
									<?php echo $this->getChildHtml('customer_form_mini_login'); ?>
								</li>
								<?php } else{?>
									<div class="block-action-header top-link-account parent-link my-account-link">
										<ul>
											<li>
												<a class="account-toplink dropdown-ict" title="<?php echo $this->__('My Account')?>" href="<?php echo $this->getUrl('customer/account')?>" style="color:white;"><i class="fa fa-user" style="color:white;"></i><?php echo $this->__(' Hello %s', Mage::getSingleton('customer/session')->getCustomer()->getFirstname()) ?></a>
												<?php echo $this->getChildHtml('account_links'); ?>
											</li>
										</ul>
									</div>
								<?php } ?>
							</ul>
						</div>
                                        
                                        <div class="block-action-header top-link-account search-box" style="float:right;">
                                            <span class="search_logo"><img src="<?php echo Mage::getBaseUrl('media').'/sm/search-icon.png'?>" style="height:28px; margin-top:5px;"></span>
                                           <div style="display: none; height:25px; width:250px; margin-top:5px; margin-right:4px; background-color: white; " class="search-item">
                                               <form id="search_mini_form" action="<?php echo Mage::getUrl('product/index/search') ?>" method="get">
                                                    <img src="<?php echo Mage::getBaseUrl('media').'/sm/search-icon-logo.png'?>" style="height:20px; margin-top:-1px">
                                                    <input type="text" name="q" id="search" class="fiestic-search" style="height:22px; outline:none; border:none !important;">
                                                    <!--<div class="selectParent" style="display:inline; "><select name="" style="display:inline; ">
                                                       <option value="Book" selected>Books</option>
                                                       <option value="Music">Music</option>
                                                       <option value="Film">Film</option>
                                                        </select></div>-->
                                                    <img src="<?php echo Mage::getBaseUrl('media').'/sm/searchbox-close.png'?>" style="height:12px; margin-top:0px;" class="searchbox_hide">
                                               </form>
                                           </div>
						</div>
                                        <script>
                                            jQuery(document).ready(function($){
                                                
       jQuery('.search_logo').click(function(){
jQuery('.search_logo').css('display','none');  
jQuery('.search-item').show();
            
        });
                       
                jQuery('.searchbox_hide').click(function(){
jQuery('.search_logo').css('display','block');  
jQuery('.search-item').css('display','none');
            
        });
                                                
                                                
                                            });
                                            </script>

					</div>

					<div class="action-mobile">
						<div class="block-action-header top-link-account my-account-link account-mobile-btn">
							<ul>
								<li>
									<a title="<?php echo $this->__('My Account')?>" href="<?php echo $this->getUrl('customer/account')?>"><i class="fa fa-user" style="color:white;"></i></a>
								</li>
							</ul>
							<div class="dropdown-mobile">
								<?php echo $this->getChildHtml('topLinks');?>
								<?php echo $this->getChildHtml('account_links'); ?>
								<ul class="block-action-header top-link-account login-link">
									<?php if(!$this->helper('customer')->isLoggedIn()){?>
									<li>
										<a class="login-btn" href="<?php echo $this->getUrl('customer/account/login')?>" title="<?php echo $this->__('Login')?>"><?php echo $this->__('Login')?></a>
									</li>
									<?php } else{?>
									<li>
										<a class="logout-btn" href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo $this->__('Logout');?>"><?php echo $this->__('Logout');?></a>
									</li>
									<?php } ?>
								</ul>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="yt-header-under">
		<div class="container">
			<div class="row yt-header-under-wrap">
				<div class="col-lg-12 col-md-12 col-sm-12 logo-small-wrapper">
					<h1>
						<a title="<?php echo $this->getLogoAlt() ?>" href="<?php echo $this->getUrl('') ?>">
							<img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
						</a>
					</h1>
				</div>

				<div class="col-lg-9 col-md-9 yt-menu-wrap">
					<!--<div class="search-pro">
						<?php// echo $this->getChildHtml('searchboxpro'); ?>
					</div>-->
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	/*jQuery('.header-v2 .btn-menu-destop').click(function(){
		if(jQuery('.header-v2 .btn-menu-destop i').hasClass('fa-angle-down')){
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-down');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-up');
		} else {
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-up');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-down');
		}
		jQuery(".header-v2 .yt-menu-wrap-vertical-destop").slideToggle("fast");
	});*/
</script>

<script>
    /*
jQuery(document).ready(function(){
    var menu_books_src = jQuery(".menu_books_logo").attr('src');
     var menu_music_src = jQuery(".menu_music_logo").attr('src');
      var menu_film_src = jQuery(".menu_film_logo").attr('src');
   
        
var isHoverSpecialDiv = false;
jQuery('.book_subcategory').hover(
    function(){
        //console.log('11');
        jQuery('.book_subcategory').css("display","block");
        isHoverSpecialDiv = true;
         var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-hover.png';
        jQuery('.menu_books_logo').attr("src", src);
    },
    function(){
        
        isHoverSpecialDiv = false;
         jQuery('.menu_books_logo').attr("src", menu_books_src);
         jQuery('.book_subcategory').css("display","none");
    
});

        
        
        
        jQuery(".menu_books_logo").hover(function(){
            
         var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-hover.png';
        jQuery(this).attr("src", src);
        jQuery('.book_subcategory').css("display","block");
        
        }, function(){
            
         if(isHoverSpecialDiv == true){
            
            jQuery('.book_subcategory').css("display","block");
        
             
            
       
    }
    else{
       
         jQuery('.book_subcategory').css("display","none");
          jQuery(this).attr("src", menu_books_src);
    }
    });
    
    
    
    
    
    
    //---------------------MUSIC------------------->>
    var musicdiv = false;
jQuery('.music_subcategory').hover(
    function(){
        //console.log('11');
        jQuery('.music_subcategory').css("display","block");
        musicdiv = true;
         var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-hover.png';
        jQuery('.menu_music_logo').attr("src", src);
    },
    function(){
        
        musicdiv = false;
         jQuery('.menu_music_logo').attr("src", menu_music_src);
         jQuery('.music_subcategory').css("display","none");
    
});


    jQuery(".menu_music_logo").hover(function(){
              var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-hover.png';
        jQuery(this).attr("src", src);
         jQuery('.music_subcategory').css("display","block");
        }, function(){
          
          
           if(musicdiv == true){
              
            
            jQuery('.music_subcategory').css("display","block");
        
             
            
       
    }
    else{
       
         jQuery('.music_subcategory').css("display","none");
          jQuery(this).attr("src", menu_music_src);
    }
          
          
    });
    
    
    
    //-------------------------ENDS----------->>
    
    
    
    
    
    
    //------------------MOVIE---------------->>
    
     var filmdiv = false;
jQuery('.film_subcategory').hover(
    function(){
        //console.log('11');
        jQuery('.film_subcategory').css("display","block");
        filmdiv = true;
         var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-hover.png';
        jQuery('.menu_film_logo').attr("src", src);
    },
    function(){
        
        filmdiv = false;
         jQuery('.menu_film_logo').attr("src", menu_film_src);
         jQuery('.film_subcategory').css("display","none");
    
});


    jQuery(".menu_film_logo").hover(function(){
        
              var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-hover.png';
        jQuery(this).attr("src", src);
         jQuery('.film_subcategory').css("display","block");
        }, function(){
            
          if(filmdiv == true){
              
            
            jQuery('.film_subcategory').css("display","block");
        
             
            
       
    }
    else{
       
         jQuery('.film_subcategory').css("display","none");
          jQuery(this).attr("src", menu_film_src);
    }
    });
});    
*/
//--------------ENDS------------------------>>

/*jQuery(document).ready(function(){
    
    if(jQuery('.header-v2 .btn-menu-destop i').hasClass('fa-angle-down')){
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-down');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-up');
		} else {
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-up');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-down');
		}
		jQuery(".header-v2 .yt-menu-wrap-vertical-destop").slideToggle("fast");
    
    var menu_books_src = jQuery(".menu_books_logo").attr('src');
     var menu_music_src = jQuery(".menu_music_logo").attr('src');
      var menu_film_src = jQuery(".menu_film_logo").attr('src');
      
      
      var url      = window.location.href;  
       console.log(url);
       var books_url = '<?php echo Mage::getBaseUrl(); ?>books'
        var music_url = '<?php echo Mage::getBaseUrl(); ?>music'
         var film_url = '<?php echo Mage::getBaseUrl(); ?>film'
         console.log(books_url);
         console.log(music_url);
         console.log(film_url);
      if(url.indexOf(books_url) > -1){
          
  var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-active.png';
     jQuery('.menu_books_logo').attr("src", src);
        jQuery('.book_subcategory').css("display","block");

}

 else if(url.indexOf(music_url) > -1){
 
    var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-active.png';
     jQuery('.menu_music_logo').attr("src", src);
        jQuery('.music_subcategory').css("display","block");
}

 else if(url.indexOf(film_url) > -1){
 
 var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-active.png';
     jQuery('.menu_film_logo').attr("src", src);
        jQuery('.film_subcategory').css("display","block");
 
}
else{

        
        
        var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-active.png';
     jQuery('.menu_books_logo').attr("src", src);
        jQuery('.book_subcategory').css("display","block");
      
      }
    
    
    
    jQuery(".menu_books_logo").hover(function(){
          
          
            var src1= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-off.png';
        jQuery('.menu_music_logo').attr("src", src1);
         var src2= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-off.png';
        jQuery('.menu_film_logo').attr("src", src2);
        
            var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-hover.png';
        jQuery(this).attr("src", src);
        
        
        
        jQuery('.music_subcategory').css("display","none");
        jQuery('.film_subcategory').css("display","none");
        jQuery('.book_subcategory').css("display","block");
         
    }, function(){
              var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-active.png';
               jQuery(this).attr("src", src);
            });
            
            


    jQuery(".menu_music_logo").hover(function(){
        
        var src1= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-off.png';
        jQuery('.menu_books_logo').attr("src", src1);
         var src2= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-off.png';
        jQuery('.menu_film_logo').attr("src", src2);
        
            var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-hover.png';
        jQuery(this).attr("src", src);
        jQuery('.music_subcategory').css("display","block");
        jQuery('.film_subcategory').css("display","none");
        jQuery('.book_subcategory').css("display","none");
         
    }, function(){
               var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-active.png';
               jQuery(this).attr("src", src);
            });
            
            
              jQuery(".menu_film_logo").hover(function(){
        
        var src1= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-off.png';
        jQuery('.menu_books_logo').attr("src", src1);
         var src2= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-off.png';
        jQuery('.menu_music_logo').attr("src", src2);
        
            var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-hover.png';
        jQuery(this).attr("src", src);
        jQuery('.music_subcategory').css("display","none");
        jQuery('.film_subcategory').css("display","block");
        jQuery('.book_subcategory').css("display","none");
         
    }, function(){
               var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-active.png';
               jQuery(this).attr("src", src);
            });
      
      
    
});*/
    
    
    jQuery(document).ready(function(){
        
        /* if(jQuery('.header-v2 .btn-menu-destop i').hasClass('fa-angle-down')){
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-down');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-up');
		} else {
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-up');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-down');
		}
		jQuery(".header-v2 .yt-menu-wrap-vertical-destop").slideToggle("fast");*/
                
                
                
                
                
    //----------------Categry page link active------------->>>>
       var url      = window.location.href;  
       console.log(url);
       var books_url = '<?php echo Mage::getBaseUrl(); ?>books'
        var music_url = '<?php echo Mage::getBaseUrl(); ?>music'
         var film_url = '<?php echo Mage::getBaseUrl(); ?>film'
         console.log(books_url);
         console.log(music_url);
         console.log(film_url);
         if((url.indexOf(books_url) > -1) || (url.indexOf(music_url) > -1)  || (url.indexOf(film_url) > -1)){
        
        if(jQuery('.header-v2 .btn-menu-destop i').hasClass('fa-angle-down')){
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-down');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-up');
		} else {
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-up');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-down');
		}
		jQuery(".header-v2 .yt-menu-wrap-vertical-destop").slideToggle("fast");    
         
    
    }
    else{
        jQuery('.header-v2 .btn-menu-destop').click(function(){
		if(jQuery('.header-v2 .btn-menu-destop i').hasClass('fa-angle-down')){
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-down');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-up');
		} else {
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-up');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-down');
		}
		jQuery(".header-v2 .yt-menu-wrap-vertical-destop").slideToggle("fast");
	});
        
    }
      if(url.indexOf(books_url) > -1){
          
  
     jQuery('.menu_books_logo_off').css("display","none");
     jQuery('.menu_books_logo_active').css("display","block");
     
        jQuery('.book_subcategory').css("display","block");

}

 else if(url.indexOf(music_url) > -1){
 
    jQuery('.menu_music_logo_off').css("display","none");
     jQuery('.menu_music_logo_active').css("display","block");
        jQuery('.music_subcategory').css("display","block");
}

 else if(url.indexOf(film_url) > -1){
 
  jQuery('.menu_film_logo_off').css("display","none");
     jQuery('.menu_film_logo_active').css("display","block");
        jQuery('.film_subcategory').css("display","block");
 
}
else{

        
        
        jQuery('.menu_books_logo_off').css("display","none");
     jQuery('.menu_books_logo_active').css("display","block");
        jQuery('.book_subcategory').css("display","block");
      
      }
    //-------------------END------------------------------>>>>
        
        
        
        //-------------HOVER---------------------->>
        var prev_id;
         jQuery(".menu_books").hover(function(){
          
          
           jQuery('.menu_books_logo').each(function(){
              var css= jQuery(this).css('display');
             if(css == 'block'){
                  prev_id=jQuery(this).attr('id');
            
             }      
    });  
     jQuery('#menu_books_logo_off').css("display","none");
     jQuery('#menu_books_logo_active').css("display","none");
     jQuery('#menu_books_logo_hover').css("display","block");
        
    }, function(){
       // console.log(prev_id);
        
         jQuery('.menu_books_logo').each(function(){
            var id= jQuery(this).attr('id');
            if(id == prev_id){
                jQuery(this).css('display','block');
                //console.log('a');
            }
            else{
                 jQuery(this).css('display','none');
            }
             
         });
                     
            });
            
            
            
            
            
             jQuery(".menu_music").hover(function(){
          
          
           jQuery('.menu_music_logo').each(function(){
              var css= jQuery(this).css('display');
             if(css == 'block'){
                  prev_id=jQuery(this).attr('id');
                 // console.log(prev_id);
                    
     
                 
             }      
    });  
     jQuery('#menu_music_logo_off').css("display","none");
     jQuery('#menu_music_logo_active').css("display","none");
     jQuery('#menu_music_logo_hover').css("display","block");
        
    }, function(){
       // console.log(prev_id);
        
         jQuery('.menu_music_logo').each(function(){
            var id= jQuery(this).attr('id');
            if(id == prev_id){
                jQuery(this).css('display','block');
                //console.log('a');
            }
            else{
                 jQuery(this).css('display','none');
            }
             
         });
                     
            });
            
            
            
            
            
            
            
            
             jQuery(".menu_film").hover(function(){
          
          
           jQuery('.menu_film_logo').each(function(){
              var css= jQuery(this).css('display');
             if(css == 'block'){
                  prev_id=jQuery(this).attr('id');
                 // console.log(prev_id);
                    
     
                 
             }      
    });  
     jQuery('#menu_film_logo_off').css("display","none");
     jQuery('#menu_film_logo_active').css("display","none");
     jQuery('#menu_film_logo_hover').css("display","block");
        
    }, function(){
       // console.log(prev_id);
        
         jQuery('.menu_film_logo').each(function(){
            var id= jQuery(this).attr('id');
            if(id == prev_id){
                jQuery(this).css('display','block');
                //console.log('a');
            }
            else{
                 jQuery(this).css('display','none');
            }
             
         });
                     
            });
            
            
            
            
      /*   jQuery(".menu_books").click(function(){
             jQuery(".book_subcategory").css('display','block');
              jQuery(".music_subcategory").css('display','none');
               jQuery(".film_subcategory").css('display','none');
               
               jQuery('#menu_books_logo_active').css('display' , 'block');
                jQuery('#menu_books_logo_hover').css('display' , 'none');
                 jQuery('#menu_books_logo_off').css('display' , 'none');
   
});   */
            
            
            
            
            
            
            
            
        
       
        
        //--------------------------ENDS----------->>
    });
</script>
