<style type="text/css">
    .menu-container{color:black;}
    .menu_img{max-height:30px; max-width:px;}
    .menu_subcategory{padding-top: 20px; padding-left: 10px;}
</style>
<?php global $var_yttheme; ?>
<?php $identifier = Mage::getSingleton('cms/page')->getIdentifier();?>
<div class="header-default header-v2">
	<div class="yt-header-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-md-3 col-sm-6 logo-wrapper">
					<div class="logo-wrapper-inner">
						<h1>
							<a title="<?php echo $this->getLogoAlt() ?>" href="<?php echo $this->getUrl('') ?>">
								<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
							</a>

							<?php if ($identifier !="home-v2") {?>
							<div class="btn-menu-destop"><i class="fa fa-angle-down"></i></div>
							<?php } ?>
						</h1>
						<?php if ($identifier !="home-v2") {?>
							<div class="yt-menu-wrap-vertical-destop">
								<?php if( $var_yttheme->getParam('menustyle') == 'mega' ){
									echo $this->getChildHtml('megaMenuBtnCate');
								} else { ?>
									<div class="mega-left-title css-menu-left-title">
										<strong><?php echo $this->__('Categories')?></strong>
									</div>
<?php 
  $currentUrl = Mage::helper('core/url')->getCurrentUrl();
 //$url = Mage::getSingleton('core/url')->parseUrl($currentUrl);
// $path = $url->getPath();?>									<div class="cssMenu-vertical">
    <div class="row menu-container" style="margin-top: 12px;">
        <div class="col-lg-1 col-md-1 "></div>
        <div class="col-lg-3 col-md-3 ">
            <?php 
            trim($path);
            $url= Mage::getBaseUrl().'books.html';
            trim($url);
            trim($currentUrl);
         
            if($currentUrl == $url){
                
                 
            $src = Mage::getBaseUrl('media')."sm/icon-books-active.png";
            }  else {
                
            
            $src = Mage::getBaseUrl('media')."sm/icon-books-off.png";
            }
            ?>
            <a href="<?php echo $url;?>"><img src="<?php echo $src; ?>" class="menu_img menu_books_logo"></a></div>
        <div class="col-lg-3 col-md-3 ">
            
            <?php 
            trim($path);
            $url= Mage::getBaseUrl().'music.html';
            trim($url);
            trim($currentUrl);
         
            if($currentUrl == $url){
                
                 
            $src =Mage::getBaseUrl('media')."sm/icon-music-active.png";
            }  else {
                
            
            $src = Mage::getBaseUrl('media')."sm/icon-music-off.png";
            }
            ?>
            
            <a href="<?php echo $url;?>"> <img src="<?php echo $src; ?>" class="menu_img menu_music_logo"> </a></div>
        <div class="col-lg-3 col-md-3 ">
            
              <?php 
            trim($path);
            $url= Mage::getBaseUrl().'film.html';
            trim($url);
            trim($currentUrl);
         
            if($currentUrl == $url){
                
                 
            $src =Mage::getBaseUrl('media')."sm/icon-film-active.png";
            }  else {
                
            
            $src = Mage::getBaseUrl('media')."sm/icon-film-off.png";
            }
            ?>
            
            <a href="<?php echo $url;?>">  <img src="<?php echo $src; ?>" class="menu_img menu_film_logo"></a></div>
         <div class="col-lg-1 col-md-1 "></div>
                                                                                
                                                                                
    </div>
    <div style="color:black; display: none; margin-top:-8px;" class="book_subcategory menu_subcategory ">
        <?php
        $cat = Mage::getModel('catalog/category')->load('128');
        
        $subcats = $cat->getChildren();
        echo "<ul class='level0 shown-sub'>";
        foreach(explode(',',$subcats) as $subCatid)
{
           
  $_category = Mage::getModel('catalog/category')->load($subCatid);
  if($_category->getIsActive())
  {
     $caturl     = $_category->getURL();
    
      $catname     = $_category->getName();
   echo "<a href=".$caturl."> <li class='level1 nav-1-6'>". $catname."</li></a>";
   
  }
}
echo "</ul>";
    
        ?>
        </div>
    
    <div style="color:black; display:none; margin-top: -6px;" class="music_subcategory menu_subcategory ">
        <?php
        $cat = Mage::getModel('catalog/category')->load('129');
        
        $subcats = $cat->getChildren();
        echo "<ul class='level0 shown-sub'>";
        foreach(explode(',',$subcats) as $subCatid)
{
           
  $_category = Mage::getModel('catalog/category')->load($subCatid);
  if($_category->getIsActive())
  {
     $caturl     = $_category->getURL();
    
      $catname     = $_category->getName();
   echo "<a href=".$caturl."> <li class='level1 nav-1-6'>". $catname."</li></a>";
   
  }
}
echo "</ul>";
    
        ?>
        </div>
    <div style="color:black; display: none;" class="film_subcategory menu_subcategory ">
        <?php
        $cat = Mage::getModel('catalog/category')->load('130');
        
        $subcats = $cat->getChildren();
        echo "<ul class='level0 shown-sub'>";
        foreach(explode(',',$subcats) as $subCatid)
{
           
  $_category = Mage::getModel('catalog/category')->load($subCatid);
  if($_category->getIsActive())
  {
     $caturl     = $_category->getURL();
    
      $catname     = $_category->getName();
   echo "<a href=".$caturl."> <li class='level1 nav-1-6'>". $catname."</li></a>";
   
  }
}
echo "</ul>";
    
        ?>
        </div>
										<!--<?php// echo $this->getChildHtml('topMenu');?>-->
									</div>
								<?php } ?>
							</div>
						<?php } ?>
					</div>
				</div>
				<div class="col-lg-3 col-md-3 col-sm-3 wrap-menu-mobi">
					<div id="yt-responsivemenu" class="yt-responsivemenu">
						<?php echo $this->getChildHtml('mobiMenu'); ?>
					</div>
				</div>
				<div class="col-lg-3 col-md-9 col-sm-6 right-wrapper">
					<div class="wrap-search-mobile">
						<a class="btn-search-mobile icon-search" href="javascript:void(0)" title="<?php echo $this->__('Search')?>"><i class="fa fa-search"></i></a>
						<script>
							jQuery(document).ready(function($){
								$( ".btn-search-mobile" ).click(function() {
									$('.search-pro').toggleClass('show')
									$(this).toggleClass('active')
								});
							});
						</script>
					</div>
					<?php echo $this->getChildHtml('currency'); ?>
					<?php echo $this->getChildHtml('store_language') ?>
					<div class="top-links-action">

						<div class="block-action-header top-link-account login-link">
							<ul>
								<?php if(!$this->helper('customer')->isLoggedIn()){?>
								<li>
									<a class="login-btn" data-toggle="modal" data-target="#modal-login" title="<?php echo $this->__('Login')?>"><i class="fa fa-user"></i><?php echo $this->__(' Login')?></a>
									<?php echo $this->getChildHtml('customer_form_mini_login'); ?>
								</li>
								<?php } else{?>
									<div class="block-action-header top-link-account parent-link my-account-link">
										<ul>
											<li>
												<a class="account-toplink dropdown-ict" title="<?php echo $this->__('My Account')?>" href="<?php echo $this->getUrl('customer/account')?>"><i class="fa fa-user"></i><?php echo $this->__(' Hi %s', Mage::getSingleton('customer/session')->getCustomer()->getFirstname()) ?></a>
												<?php echo $this->getChildHtml('account_links'); ?>
											</li>
										</ul>
									</div>
								<?php } ?>
							</ul>
						</div>

					</div>

					<div class="mini-cart-header">
						<?php echo $this->getChildHtml('mini-cartpro') ?>
					</div>

					<div class="action-mobile">
						<div class="block-action-header top-link-account my-account-link account-mobile-btn">
							<ul>
								<li>
									<a title="<?php echo $this->__('My Account')?>" href="<?php echo $this->getUrl('customer/account')?>"><i class="fa fa-user"></i></a>
								</li>
							</ul>
							<div class="dropdown-mobile">
								<?php echo $this->getChildHtml('topLinks');?>
								<?php echo $this->getChildHtml('account_links'); ?>
								<ul class="block-action-header top-link-account login-link">
									<?php if(!$this->helper('customer')->isLoggedIn()){?>
									<li>
										<a class="login-btn" href="<?php echo $this->getUrl('customer/account/login')?>" title="<?php echo $this->__('Login')?>"><?php echo $this->__('Login')?></a>
									</li>
									<?php } else{?>
									<li>
										<a class="logout-btn" href="<?php echo $this->getUrl('customer/account/logout')?>" title="<?php echo $this->__('Logout');?>"><?php echo $this->__('Logout');?></a>
									</li>
									<?php } ?>
								</ul>
							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="yt-header-under">
		<div class="container">
			<div class="row yt-header-under-wrap">
				<div class="col-lg-12 col-md-12 col-sm-12 logo-small-wrapper">
					<h1>
						<a title="<?php echo $this->getLogoAlt() ?>" href="<?php echo $this->getUrl('') ?>">
							<img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
						</a>
					</h1>
				</div>

				<div class="col-lg-9 col-md-9 yt-menu-wrap">
					<div class="search-pro">
						<?php echo $this->getChildHtml('searchboxpro'); ?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	/*jQuery('.header-v2 .btn-menu-destop').click(function(){
		if(jQuery('.header-v2 .btn-menu-destop i').hasClass('fa-angle-down')){
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-down');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-up');
		} else {
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-up');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-down');
		}
		jQuery(".header-v2 .yt-menu-wrap-vertical-destop").slideToggle("fast");
	});*/
</script>

<script>
    /*
jQuery(document).ready(function(){
    var menu_books_src = jQuery(".menu_books_logo").attr('src');
     var menu_music_src = jQuery(".menu_music_logo").attr('src');
      var menu_film_src = jQuery(".menu_film_logo").attr('src');
   
        
var isHoverSpecialDiv = false;
jQuery('.book_subcategory').hover(
    function(){
        //console.log('11');
        jQuery('.book_subcategory').css("display","block");
        isHoverSpecialDiv = true;
         var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-hover.png';
        jQuery('.menu_books_logo').attr("src", src);
    },
    function(){
        
        isHoverSpecialDiv = false;
         jQuery('.menu_books_logo').attr("src", menu_books_src);
         jQuery('.book_subcategory').css("display","none");
    
});

        
        
        
        jQuery(".menu_books_logo").hover(function(){
            
         var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-hover.png';
        jQuery(this).attr("src", src);
        jQuery('.book_subcategory').css("display","block");
        
        }, function(){
            
         if(isHoverSpecialDiv == true){
            
            jQuery('.book_subcategory').css("display","block");
        
             
            
       
    }
    else{
       
         jQuery('.book_subcategory').css("display","none");
          jQuery(this).attr("src", menu_books_src);
    }
    });
    
    
    
    
    
    
    //---------------------MUSIC------------------->>
    var musicdiv = false;
jQuery('.music_subcategory').hover(
    function(){
        //console.log('11');
        jQuery('.music_subcategory').css("display","block");
        musicdiv = true;
         var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-hover.png';
        jQuery('.menu_music_logo').attr("src", src);
    },
    function(){
        
        musicdiv = false;
         jQuery('.menu_music_logo').attr("src", menu_music_src);
         jQuery('.music_subcategory').css("display","none");
    
});


    jQuery(".menu_music_logo").hover(function(){
              var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-hover.png';
        jQuery(this).attr("src", src);
         jQuery('.music_subcategory').css("display","block");
        }, function(){
          
          
           if(musicdiv == true){
              
            
            jQuery('.music_subcategory').css("display","block");
        
             
            
       
    }
    else{
       
         jQuery('.music_subcategory').css("display","none");
          jQuery(this).attr("src", menu_music_src);
    }
          
          
    });
    
    
    
    //-------------------------ENDS----------->>
    
    
    
    
    
    
    //------------------MOVIE---------------->>
    
     var filmdiv = false;
jQuery('.film_subcategory').hover(
    function(){
        //console.log('11');
        jQuery('.film_subcategory').css("display","block");
        filmdiv = true;
         var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-hover.png';
        jQuery('.menu_film_logo').attr("src", src);
    },
    function(){
        
        filmdiv = false;
         jQuery('.menu_film_logo').attr("src", menu_film_src);
         jQuery('.film_subcategory').css("display","none");
    
});


    jQuery(".menu_film_logo").hover(function(){
        
              var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-hover.png';
        jQuery(this).attr("src", src);
         jQuery('.film_subcategory').css("display","block");
        }, function(){
            
          if(filmdiv == true){
              
            
            jQuery('.film_subcategory').css("display","block");
        
             
            
       
    }
    else{
       
         jQuery('.film_subcategory').css("display","none");
          jQuery(this).attr("src", menu_film_src);
    }
    });
});    
*/
//--------------ENDS------------------------>>

jQuery(document).ready(function(){
    
    if(jQuery('.header-v2 .btn-menu-destop i').hasClass('fa-angle-down')){
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-down');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-up');
		} else {
			jQuery('.header-v2 .btn-menu-destop i').removeClass('fa-angle-up');
			jQuery('.header-v2 .btn-menu-destop i').addClass('fa-angle-down');
		}
		jQuery(".header-v2 .yt-menu-wrap-vertical-destop").slideToggle("fast");
    
    var menu_books_src = jQuery(".menu_books_logo").attr('src');
     var menu_music_src = jQuery(".menu_music_logo").attr('src');
      var menu_film_src = jQuery(".menu_film_logo").attr('src');
      
      
      var url      = window.location.href;  
       console.log(url);
       var books_url = '<?php echo Mage::getBaseUrl(); ?>books'
        var music_url = '<?php echo Mage::getBaseUrl(); ?>music'
         var film_url = '<?php echo Mage::getBaseUrl(); ?>film'
         console.log(books_url);
         console.log(music_url);
         console.log(film_url);
      if(url.indexOf(books_url) > -1){
          
  var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-active.png';
     jQuery('.menu_books_logo').attr("src", src);
        jQuery('.book_subcategory').css("display","block");

}

 else if(url.indexOf(music_url) > -1){
 
    var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-active.png';
     jQuery('.menu_music_logo').attr("src", src);
        jQuery('.music_subcategory').css("display","block");
}

 else if(url.indexOf(film_url) > -1){
 
 var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-active.png';
     jQuery('.menu_film_logo').attr("src", src);
        jQuery('.film_subcategory').css("display","block");
 
}
else{

        
        
        var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-active.png';
     jQuery('.menu_books_logo').attr("src", src);
        jQuery('.book_subcategory').css("display","block");
      
      }
    
    
    
    jQuery(".menu_books_logo").hover(function(){
          
          
            var src1= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-off.png';
        jQuery('.menu_music_logo').attr("src", src1);
         var src2= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-off.png';
        jQuery('.menu_film_logo').attr("src", src2);
        
            var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-hover.png';
        jQuery(this).attr("src", src);
        
        
        
        jQuery('.music_subcategory').css("display","none");
        jQuery('.film_subcategory').css("display","none");
        jQuery('.book_subcategory').css("display","block");
         
    }, function(){
              var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-active.png';
               jQuery(this).attr("src", src);
            });
            
            


    jQuery(".menu_music_logo").hover(function(){
        
        var src1= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-off.png';
        jQuery('.menu_books_logo').attr("src", src1);
         var src2= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-off.png';
        jQuery('.menu_film_logo').attr("src", src2);
        
            var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-hover.png';
        jQuery(this).attr("src", src);
        jQuery('.music_subcategory').css("display","block");
        jQuery('.film_subcategory').css("display","none");
        jQuery('.book_subcategory').css("display","none");
         
    }, function(){
               var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-active.png';
               jQuery(this).attr("src", src);
            });
            
            
              jQuery(".menu_film_logo").hover(function(){
        
        var src1= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-books-off.png';
        jQuery('.menu_books_logo').attr("src", src1);
         var src2= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-music-off.png';
        jQuery('.menu_music_logo').attr("src", src2);
        
            var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-hover.png';
        jQuery(this).attr("src", src);
        jQuery('.music_subcategory').css("display","none");
        jQuery('.film_subcategory').css("display","block");
        jQuery('.book_subcategory').css("display","none");
         
    }, function(){
               var src= '<?php  echo Mage::getBaseUrl('media');?>'+'sm/icon-film-active.png';
               jQuery(this).attr("src", src);
            });
      
      
    
});
</script>
